nodeLinker: node-modules

npmRegistries:
  "https://npm.greensock.com":
    npmAlwaysAuth: true
    npmAuthToken: b5fe5405-22ea-4c3b-a8f0-830ff14eb8c8

npmScopes:
  gsap:
    npmAlwaysAuth: true
    npmAuthToken: b5fe5405-22ea-4c3b-a8f0-830ff14eb8c8
    npmRegistryServer: "https://npm.greensock.com"

yarnPath: .yarn/releases/yarn-4.2.2.cjs
